/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardProjectsIndexRouteImport } from './routes/_dashboard/projects/index'
import { Route as DashboardDesignSystemsIndexRouteImport } from './routes/_dashboard/design-systems/index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/_dashboard/projects/$projectId'
import { Route as DashboardDesignSystemsSystemIdRouteImport } from './routes/_dashboard/design-systems/$systemId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDesignSystemsIndexRoute =
  DashboardDesignSystemsIndexRouteImport.update({
    id: '/design-systems/',
    path: '/design-systems/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDesignSystemsSystemIdRoute =
  DashboardDesignSystemsSystemIdRouteImport.update({
    id: '/design-systems/$systemId',
    path: '/design-systems/$systemId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/share/$token': typeof ShareTokenRoute
  '/design-systems/$systemId': typeof DashboardDesignSystemsSystemIdRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/design-systems/': typeof DashboardDesignSystemsIndexRoute
  '/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/share/$token': typeof ShareTokenRoute
  '/design-systems/$systemId': typeof DashboardDesignSystemsSystemIdRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/design-systems': typeof DashboardDesignSystemsIndexRoute
  '/projects': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/share/$token': typeof ShareTokenRoute
  '/_dashboard/design-systems/$systemId': typeof DashboardDesignSystemsSystemIdRoute
  '/_dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/_dashboard/design-systems/': typeof DashboardDesignSystemsIndexRoute
  '/_dashboard/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/register'
    | '/share/$token'
    | '/design-systems/$systemId'
    | '/projects/$projectId'
    | '/design-systems/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/login'
    | '/register'
    | '/share/$token'
    | '/design-systems/$systemId'
    | '/projects/$projectId'
    | '/design-systems'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/settings'
    | '/_auth/login'
    | '/_auth/register'
    | '/share/$token'
    | '/_dashboard/design-systems/$systemId'
    | '/_dashboard/projects/$projectId'
    | '/_dashboard/design-systems/'
    | '/_dashboard/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/design-systems/': {
      id: '/_dashboard/design-systems/'
      path: '/design-systems'
      fullPath: '/design-systems/'
      preLoaderRoute: typeof DashboardDesignSystemsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/$projectId': {
      id: '/_dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/design-systems/$systemId': {
      id: '/_dashboard/design-systems/$systemId'
      path: '/design-systems/$systemId'
      fullPath: '/design-systems/$systemId'
      preLoaderRoute: typeof DashboardDesignSystemsSystemIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardDesignSystemsSystemIdRoute: typeof DashboardDesignSystemsSystemIdRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardDesignSystemsIndexRoute: typeof DashboardDesignSystemsIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDesignSystemsSystemIdRoute: DashboardDesignSystemsSystemIdRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardDesignSystemsIndexRoute: DashboardDesignSystemsIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
